# Generated by Django 3.2 on 2026-04-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0003_movie_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='zh_genres',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='zh_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
